# Generated by Django 4.2.7 on 2025-03-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='billing_period',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=20),
        ),
    ]
