# Generated by Django 4.2.7 on 2025-03-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_tariff_alter_bill_billing_period_alter_bill_status'),
        ('billing', '0002_tariff_alter_bill_status'),
    ]

    operations = [
    ]
