# Generated by Django 5.2.4 on 2025-07-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbill',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Penalty amount for late payment', max_digits=10, verbose_name='Penalty Amount'),
        ),
    ]
