# Generated by Django 5.2.4 on 2025-07-27 23:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_waterbill_penalty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Amount must be greater than 0')], verbose_name='Amount (KES)')),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], help_text='Payment method used', max_length=20, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, help_text='Reference number for the payment (e.g., M-Pesa code, bank reference)', max_length=100, null=True, verbose_name='Reference Number')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when payment was made', verbose_name='Payment Date')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this payment', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(blank=True, help_text='Optional: Link to the bill being paid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='main.waterbill', verbose_name='Bill')),
                ('recorded_by', models.ForeignKey(help_text='Staff who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
