# Generated by Django 3.0.5 on 2025-07-28 16:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20250728_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_value', models.DecimalField(decimal_places=2, help_text='The meter reading value in cubic meters (m³)', max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'Reading cannot be negative')])),
                ('reading_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the reading was taken')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this reading', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(help_text='User who recorded this reading', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_readings', to=settings.AUTH_USER_MODEL)),
                ('water_bill', models.OneToOneField(blank=True, help_text='The water bill this reading is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter_reading', to='main.WaterBill')),
            ],
            options={
                'verbose_name': 'Meter Reading',
                'verbose_name_plural': 'Meter Readings',
                'ordering': ['-reading_date'],
            },
        ),
    ]
