# Generated by Django 3.0.5 on 2025-07-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_meterreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='meter_photo',
            field=models.ImageField(blank=True, help_text='Photo of the meter reading', null=True, upload_to='meter_readings/', verbose_name='Meter Photo'),
        ),
    ]
