# Generated by Django 3.0.5 on 2025-07-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_meterreading_meter_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterreading',
            name='meter_photo',
        ),
    ]
