# Generated by Django 4.2.7 on 2025-03-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meterreading',
            options={'ordering': ['-reading_date']},
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
